(define (letterGrade grade)
    (cond
        ((< grade 60) "F")
        ((< grade 70) "D")
        ((< grade 80) "C")
        ((< grade 90) "B")
        (else "D")
    )
)

(define (main)
    (display (letterGrade 0))
    (newline)
    (display (letterGrade 75))
    (newline)
    (display (letterGrade 95))
)
(main)
(exit)